# Generated by Django 4.2.28 on 2026-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_market', '0002_order_productinorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='picture.png', upload_to='product_images'),
        ),
    ]
